#Question 1> what is the total revenue generated by male vs female customers? 
select gender,sum(purchase_amount) as renevue from customer group by gender;


select*from customer;

#question 2> which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer 
where discount_applied = 'yes' and purchase_amount 
>= (select Avg(purchase_amount) from customer);

#question 3>which are the top 5 products with the highest average review rating
select item_purchased , avg(review_rating) from customer
group by item_purchased
order by avg(review_rating) desc limit 5;


#Question 4> compare the average purchase amounts between Standard and Express Shipping.

select shipping_type,ROUND (avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

#Question 5> Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers

select subscription_status, count(customer_id),
ROUND(avg(purchase_amount),2)as avg_spend,
ROUND(sum(purchase_amount),2)as total_revenue
from customer group by subscription_status
order by avg_spend,total_revenue desc;

#Question 6> which 5 products have the highest percentage of purchase with discounts applied?

select item_purchased, ROUND(100 * sum(CASE WHEN discount_applied='yes' THEN 1 ELSE 0 END)/count(*),2)
as discount_rate from customer group by item_purchased 
order by discount_rate desc	limit 5;

#Question 7> segment customer into new, returning, and loyal based on their total number of previous 
#purchases, and show the count of each segment.

with customer_types as (
select customer_id,previous_purchases,
CASE
	when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer
);

select customer_segment, count(*) as "number of customers"
from customer_types group by customer_segment

# Question 8> what are the top 3 most purchased products within each category?

with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count (customer_id)desc)
as item_rank from customer group by category, item_purchased
);

select item_rank, category, item_purchased, total_orders
from item_counts where item_rank <=	3;

#Question 9> Are customer who are repeats buyers (more than 5 previous purchase) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases > 5 group by subscription_status;

# Question 10> what is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer group by age_group
order by total_revenue
